name: Release VSIX

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Package VSIX
        run: npx --yes @vscode/vsce package --no-yarn

      # 👇 sanity: confirm VSIX exists in workspace root
      - name: List vsix
        run: |
          pwd
          ls -lah
          ls -lah *.vsix || true

      - name: Create GitHub Release & upload VSIX
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: "commitaiflow-*.vsix"
          generate_release_notes: true