name: Release VSIX

on:
  push:
    tags:
      - 'v*.*.*'   # 例如 v0.0.1

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 允许创建 Release 并上传资源
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Package VSIX
        run: npx vsce package --no-yarn

      - name: Create GitHub Release & upload VSIX
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          draft: false
          prerelease: false
