name: Release VSIX

on:
  push:
    tags: ['v*.*.*']   # trigger when a new semver tag is pushed
  workflow_dispatch:    # allow manual run (choose a tag below)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # REQUIRED to create/upload releases
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # get tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Package VSIX
        run: npx --yes @vscode/vsce package --no-yarn

      - name: Create GitHub Release & upload VSIX
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
          generate_release_notes: true
          # If you run manually, this will use the ref/tag of the run automatically.